# Generated by Django 4.2.2 on 2023-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_map_name_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
