# Generated by Django 4.2.2 on 2023-06-19 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=datetime.datetime(2023, 6, 19, 17, 4, 15, 750495, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
