# Generated by Django 4.2.2 on 2023-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('user', '0003_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(to='game.hero'),
        ),
    ]
